// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transportinstruction.proto

package com.toocol.ssh.core.mosh.core.proto;

public final class InstructionPB {
  private InstructionPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InstructionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransportBuffers.Instruction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 protocol_version = 1;</code>
     * @return Whether the protocolVersion field is set.
     */
    boolean hasProtocolVersion();
    /**
     * <code>optional uint32 protocol_version = 1;</code>
     * @return The protocolVersion.
     */
    int getProtocolVersion();

    /**
     * <code>optional uint64 old_num = 2;</code>
     * @return Whether the oldNum field is set.
     */
    boolean hasOldNum();
    /**
     * <code>optional uint64 old_num = 2;</code>
     * @return The oldNum.
     */
    long getOldNum();

    /**
     * <code>optional uint64 new_num = 3;</code>
     * @return Whether the newNum field is set.
     */
    boolean hasNewNum();
    /**
     * <code>optional uint64 new_num = 3;</code>
     * @return The newNum.
     */
    long getNewNum();

    /**
     * <code>optional uint64 ack_num = 4;</code>
     * @return Whether the ackNum field is set.
     */
    boolean hasAckNum();
    /**
     * <code>optional uint64 ack_num = 4;</code>
     * @return The ackNum.
     */
    long getAckNum();

    /**
     * <code>optional uint64 throwaway_num = 5;</code>
     * @return Whether the throwawayNum field is set.
     */
    boolean hasThrowawayNum();
    /**
     * <code>optional uint64 throwaway_num = 5;</code>
     * @return The throwawayNum.
     */
    long getThrowawayNum();

    /**
     * <code>optional bytes diff = 6;</code>
     * @return Whether the diff field is set.
     */
    boolean hasDiff();
    /**
     * <code>optional bytes diff = 6;</code>
     * @return The diff.
     */
    com.google.protobuf.ByteString getDiff();

    /**
     * <code>optional bytes chaff = 7;</code>
     * @return Whether the chaff field is set.
     */
    boolean hasChaff();
    /**
     * <code>optional bytes chaff = 7;</code>
     * @return The chaff.
     */
    com.google.protobuf.ByteString getChaff();
  }
  /**
   * Protobuf type {@code TransportBuffers.Instruction}
   */
  public static final class Instruction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TransportBuffers.Instruction)
      InstructionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Instruction.newBuilder() to construct.
    private Instruction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Instruction() {
      diff_ = com.google.protobuf.ByteString.EMPTY;
      chaff_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Instruction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Instruction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              protocolVersion_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              oldNum_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              newNum_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ackNum_ = input.readUInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              throwawayNum_ = input.readUInt64();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              diff_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              chaff_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.toocol.ssh.core.mosh.core.proto.InstructionPB.internal_static_TransportBuffers_Instruction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.toocol.ssh.core.mosh.core.proto.InstructionPB.internal_static_TransportBuffers_Instruction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction.class, com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction.Builder.class);
    }

    private int bitField0_;
    public static final int PROTOCOL_VERSION_FIELD_NUMBER = 1;
    private int protocolVersion_;
    /**
     * <code>optional uint32 protocol_version = 1;</code>
     * @return Whether the protocolVersion field is set.
     */
    @java.lang.Override
    public boolean hasProtocolVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 protocol_version = 1;</code>
     * @return The protocolVersion.
     */
    @java.lang.Override
    public int getProtocolVersion() {
      return protocolVersion_;
    }

    public static final int OLD_NUM_FIELD_NUMBER = 2;
    private long oldNum_;
    /**
     * <code>optional uint64 old_num = 2;</code>
     * @return Whether the oldNum field is set.
     */
    @java.lang.Override
    public boolean hasOldNum() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint64 old_num = 2;</code>
     * @return The oldNum.
     */
    @java.lang.Override
    public long getOldNum() {
      return oldNum_;
    }

    public static final int NEW_NUM_FIELD_NUMBER = 3;
    private long newNum_;
    /**
     * <code>optional uint64 new_num = 3;</code>
     * @return Whether the newNum field is set.
     */
    @java.lang.Override
    public boolean hasNewNum() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint64 new_num = 3;</code>
     * @return The newNum.
     */
    @java.lang.Override
    public long getNewNum() {
      return newNum_;
    }

    public static final int ACK_NUM_FIELD_NUMBER = 4;
    private long ackNum_;
    /**
     * <code>optional uint64 ack_num = 4;</code>
     * @return Whether the ackNum field is set.
     */
    @java.lang.Override
    public boolean hasAckNum() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional uint64 ack_num = 4;</code>
     * @return The ackNum.
     */
    @java.lang.Override
    public long getAckNum() {
      return ackNum_;
    }

    public static final int THROWAWAY_NUM_FIELD_NUMBER = 5;
    private long throwawayNum_;
    /**
     * <code>optional uint64 throwaway_num = 5;</code>
     * @return Whether the throwawayNum field is set.
     */
    @java.lang.Override
    public boolean hasThrowawayNum() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint64 throwaway_num = 5;</code>
     * @return The throwawayNum.
     */
    @java.lang.Override
    public long getThrowawayNum() {
      return throwawayNum_;
    }

    public static final int DIFF_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString diff_;
    /**
     * <code>optional bytes diff = 6;</code>
     * @return Whether the diff field is set.
     */
    @java.lang.Override
    public boolean hasDiff() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bytes diff = 6;</code>
     * @return The diff.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDiff() {
      return diff_;
    }

    public static final int CHAFF_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString chaff_;
    /**
     * <code>optional bytes chaff = 7;</code>
     * @return Whether the chaff field is set.
     */
    @java.lang.Override
    public boolean hasChaff() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional bytes chaff = 7;</code>
     * @return The chaff.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getChaff() {
      return chaff_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, protocolVersion_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt64(2, oldNum_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt64(3, newNum_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt64(4, ackNum_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt64(5, throwawayNum_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeBytes(6, diff_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeBytes(7, chaff_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, protocolVersion_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, oldNum_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, newNum_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, ackNum_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, throwawayNum_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, diff_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, chaff_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction)) {
        return super.equals(obj);
      }
      com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction other = (com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction) obj;

      if (hasProtocolVersion() != other.hasProtocolVersion()) return false;
      if (hasProtocolVersion()) {
        if (getProtocolVersion()
            != other.getProtocolVersion()) return false;
      }
      if (hasOldNum() != other.hasOldNum()) return false;
      if (hasOldNum()) {
        if (getOldNum()
            != other.getOldNum()) return false;
      }
      if (hasNewNum() != other.hasNewNum()) return false;
      if (hasNewNum()) {
        if (getNewNum()
            != other.getNewNum()) return false;
      }
      if (hasAckNum() != other.hasAckNum()) return false;
      if (hasAckNum()) {
        if (getAckNum()
            != other.getAckNum()) return false;
      }
      if (hasThrowawayNum() != other.hasThrowawayNum()) return false;
      if (hasThrowawayNum()) {
        if (getThrowawayNum()
            != other.getThrowawayNum()) return false;
      }
      if (hasDiff() != other.hasDiff()) return false;
      if (hasDiff()) {
        if (!getDiff()
            .equals(other.getDiff())) return false;
      }
      if (hasChaff() != other.hasChaff()) return false;
      if (hasChaff()) {
        if (!getChaff()
            .equals(other.getChaff())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProtocolVersion()) {
        hash = (37 * hash) + PROTOCOL_VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getProtocolVersion();
      }
      if (hasOldNum()) {
        hash = (37 * hash) + OLD_NUM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getOldNum());
      }
      if (hasNewNum()) {
        hash = (37 * hash) + NEW_NUM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNewNum());
      }
      if (hasAckNum()) {
        hash = (37 * hash) + ACK_NUM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAckNum());
      }
      if (hasThrowawayNum()) {
        hash = (37 * hash) + THROWAWAY_NUM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getThrowawayNum());
      }
      if (hasDiff()) {
        hash = (37 * hash) + DIFF_FIELD_NUMBER;
        hash = (53 * hash) + getDiff().hashCode();
      }
      if (hasChaff()) {
        hash = (37 * hash) + CHAFF_FIELD_NUMBER;
        hash = (53 * hash) + getChaff().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransportBuffers.Instruction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransportBuffers.Instruction)
        com.toocol.ssh.core.mosh.core.proto.InstructionPB.InstructionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.toocol.ssh.core.mosh.core.proto.InstructionPB.internal_static_TransportBuffers_Instruction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.toocol.ssh.core.mosh.core.proto.InstructionPB.internal_static_TransportBuffers_Instruction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction.class, com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction.Builder.class);
      }

      // Construct using com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        protocolVersion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        oldNum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        newNum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        ackNum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        throwawayNum_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        diff_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        chaff_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.toocol.ssh.core.mosh.core.proto.InstructionPB.internal_static_TransportBuffers_Instruction_descriptor;
      }

      @java.lang.Override
      public com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction getDefaultInstanceForType() {
        return com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction.getDefaultInstance();
      }

      @java.lang.Override
      public com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction build() {
        com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction buildPartial() {
        com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction result = new com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.protocolVersion_ = protocolVersion_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.oldNum_ = oldNum_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.newNum_ = newNum_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.ackNum_ = ackNum_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.throwawayNum_ = throwawayNum_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.diff_ = diff_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.chaff_ = chaff_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction) {
          return mergeFrom((com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction other) {
        if (other == com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction.getDefaultInstance()) return this;
        if (other.hasProtocolVersion()) {
          setProtocolVersion(other.getProtocolVersion());
        }
        if (other.hasOldNum()) {
          setOldNum(other.getOldNum());
        }
        if (other.hasNewNum()) {
          setNewNum(other.getNewNum());
        }
        if (other.hasAckNum()) {
          setAckNum(other.getAckNum());
        }
        if (other.hasThrowawayNum()) {
          setThrowawayNum(other.getThrowawayNum());
        }
        if (other.hasDiff()) {
          setDiff(other.getDiff());
        }
        if (other.hasChaff()) {
          setChaff(other.getChaff());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int protocolVersion_ ;
      /**
       * <code>optional uint32 protocol_version = 1;</code>
       * @return Whether the protocolVersion field is set.
       */
      @java.lang.Override
      public boolean hasProtocolVersion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 protocol_version = 1;</code>
       * @return The protocolVersion.
       */
      @java.lang.Override
      public int getProtocolVersion() {
        return protocolVersion_;
      }
      /**
       * <code>optional uint32 protocol_version = 1;</code>
       * @param value The protocolVersion to set.
       * @return This builder for chaining.
       */
      public Builder setProtocolVersion(int value) {
        bitField0_ |= 0x00000001;
        protocolVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 protocol_version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocolVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protocolVersion_ = 0;
        onChanged();
        return this;
      }

      private long oldNum_ ;
      /**
       * <code>optional uint64 old_num = 2;</code>
       * @return Whether the oldNum field is set.
       */
      @java.lang.Override
      public boolean hasOldNum() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional uint64 old_num = 2;</code>
       * @return The oldNum.
       */
      @java.lang.Override
      public long getOldNum() {
        return oldNum_;
      }
      /**
       * <code>optional uint64 old_num = 2;</code>
       * @param value The oldNum to set.
       * @return This builder for chaining.
       */
      public Builder setOldNum(long value) {
        bitField0_ |= 0x00000002;
        oldNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 old_num = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOldNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        oldNum_ = 0L;
        onChanged();
        return this;
      }

      private long newNum_ ;
      /**
       * <code>optional uint64 new_num = 3;</code>
       * @return Whether the newNum field is set.
       */
      @java.lang.Override
      public boolean hasNewNum() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional uint64 new_num = 3;</code>
       * @return The newNum.
       */
      @java.lang.Override
      public long getNewNum() {
        return newNum_;
      }
      /**
       * <code>optional uint64 new_num = 3;</code>
       * @param value The newNum to set.
       * @return This builder for chaining.
       */
      public Builder setNewNum(long value) {
        bitField0_ |= 0x00000004;
        newNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 new_num = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNewNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        newNum_ = 0L;
        onChanged();
        return this;
      }

      private long ackNum_ ;
      /**
       * <code>optional uint64 ack_num = 4;</code>
       * @return Whether the ackNum field is set.
       */
      @java.lang.Override
      public boolean hasAckNum() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional uint64 ack_num = 4;</code>
       * @return The ackNum.
       */
      @java.lang.Override
      public long getAckNum() {
        return ackNum_;
      }
      /**
       * <code>optional uint64 ack_num = 4;</code>
       * @param value The ackNum to set.
       * @return This builder for chaining.
       */
      public Builder setAckNum(long value) {
        bitField0_ |= 0x00000008;
        ackNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 ack_num = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAckNum() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ackNum_ = 0L;
        onChanged();
        return this;
      }

      private long throwawayNum_ ;
      /**
       * <code>optional uint64 throwaway_num = 5;</code>
       * @return Whether the throwawayNum field is set.
       */
      @java.lang.Override
      public boolean hasThrowawayNum() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional uint64 throwaway_num = 5;</code>
       * @return The throwawayNum.
       */
      @java.lang.Override
      public long getThrowawayNum() {
        return throwawayNum_;
      }
      /**
       * <code>optional uint64 throwaway_num = 5;</code>
       * @param value The throwawayNum to set.
       * @return This builder for chaining.
       */
      public Builder setThrowawayNum(long value) {
        bitField0_ |= 0x00000010;
        throwawayNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 throwaway_num = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearThrowawayNum() {
        bitField0_ = (bitField0_ & ~0x00000010);
        throwawayNum_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString diff_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes diff = 6;</code>
       * @return Whether the diff field is set.
       */
      @java.lang.Override
      public boolean hasDiff() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional bytes diff = 6;</code>
       * @return The diff.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getDiff() {
        return diff_;
      }
      /**
       * <code>optional bytes diff = 6;</code>
       * @param value The diff to set.
       * @return This builder for chaining.
       */
      public Builder setDiff(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        diff_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes diff = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDiff() {
        bitField0_ = (bitField0_ & ~0x00000020);
        diff_ = getDefaultInstance().getDiff();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString chaff_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes chaff = 7;</code>
       * @return Whether the chaff field is set.
       */
      @java.lang.Override
      public boolean hasChaff() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional bytes chaff = 7;</code>
       * @return The chaff.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getChaff() {
        return chaff_;
      }
      /**
       * <code>optional bytes chaff = 7;</code>
       * @param value The chaff to set.
       * @return This builder for chaining.
       */
      public Builder setChaff(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        chaff_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes chaff = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearChaff() {
        bitField0_ = (bitField0_ & ~0x00000040);
        chaff_ = getDefaultInstance().getChaff();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TransportBuffers.Instruction)
    }

    // @@protoc_insertion_point(class_scope:TransportBuffers.Instruction)
    private static final com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction();
    }

    public static com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Instruction>
        PARSER = new com.google.protobuf.AbstractParser<Instruction>() {
      @java.lang.Override
      public Instruction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Instruction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Instruction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Instruction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.toocol.ssh.core.mosh.core.proto.InstructionPB.Instruction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransportBuffers_Instruction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransportBuffers_Instruction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032transportinstruction.proto\022\020TransportB" +
      "uffers\"\216\001\n\013Instruction\022\030\n\020protocol_versi" +
      "on\030\001 \001(\r\022\017\n\007old_num\030\002 \001(\004\022\017\n\007new_num\030\003 \001" +
      "(\004\022\017\n\007ack_num\030\004 \001(\004\022\025\n\rthrowaway_num\030\005 \001" +
      "(\004\022\014\n\004diff\030\006 \001(\014\022\r\n\005chaff\030\007 \001(\014B6\n#com.t" +
      "oocol.ssh.core.mosh.core.protoB\rInstruct" +
      "ionPBH\003"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TransportBuffers_Instruction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransportBuffers_Instruction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransportBuffers_Instruction_descriptor,
        new java.lang.String[] { "ProtocolVersion", "OldNum", "NewNum", "AckNum", "ThrowawayNum", "Diff", "Chaff", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
