// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userinput.proto

package com.toocol.ssh.core.mosh.core.proto;

public final class UserInputPB {
  private UserInputPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.toocol.ssh.core.mosh.core.proto.UserInputPB.keystroke);
    registry.add(com.toocol.ssh.core.mosh.core.proto.UserInputPB.resize);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientBuffers.UserMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
     */
    java.util.List<com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction> 
        getInstructionList();
    /**
     * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
     */
    com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction getInstruction(int index);
    /**
     * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
     */
    int getInstructionCount();
    /**
     * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
     */
    java.util.List<? extends com.toocol.ssh.core.mosh.core.proto.UserInputPB.InstructionOrBuilder> 
        getInstructionOrBuilderList();
    /**
     * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
     */
    com.toocol.ssh.core.mosh.core.proto.UserInputPB.InstructionOrBuilder getInstructionOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ClientBuffers.UserMessage}
   */
  public static final class UserMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ClientBuffers.UserMessage)
      UserMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserMessage.newBuilder() to construct.
    private UserMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserMessage() {
      instruction_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                instruction_ = new java.util.ArrayList<com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction>();
                mutable_bitField0_ |= 0x00000001;
              }
              instruction_.add(
                  input.readMessage(com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          instruction_ = java.util.Collections.unmodifiableList(instruction_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_UserMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_UserMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage.class, com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage.Builder.class);
    }

    public static final int INSTRUCTION_FIELD_NUMBER = 1;
    private java.util.List<com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction> instruction_;
    /**
     * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction> getInstructionList() {
      return instruction_;
    }
    /**
     * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.toocol.ssh.core.mosh.core.proto.UserInputPB.InstructionOrBuilder> 
        getInstructionOrBuilderList() {
      return instruction_;
    }
    /**
     * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
     */
    @java.lang.Override
    public int getInstructionCount() {
      return instruction_.size();
    }
    /**
     * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
     */
    @java.lang.Override
    public com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction getInstruction(int index) {
      return instruction_.get(index);
    }
    /**
     * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
     */
    @java.lang.Override
    public com.toocol.ssh.core.mosh.core.proto.UserInputPB.InstructionOrBuilder getInstructionOrBuilder(
        int index) {
      return instruction_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getInstructionCount(); i++) {
        if (!getInstruction(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < instruction_.size(); i++) {
        output.writeMessage(1, instruction_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < instruction_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, instruction_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage)) {
        return super.equals(obj);
      }
      com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage other = (com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage) obj;

      if (!getInstructionList()
          .equals(other.getInstructionList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getInstructionCount() > 0) {
        hash = (37 * hash) + INSTRUCTION_FIELD_NUMBER;
        hash = (53 * hash) + getInstructionList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientBuffers.UserMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientBuffers.UserMessage)
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_UserMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_UserMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage.class, com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage.Builder.class);
      }

      // Construct using com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInstructionFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (instructionBuilder_ == null) {
          instruction_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          instructionBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_UserMessage_descriptor;
      }

      @java.lang.Override
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage getDefaultInstanceForType() {
        return com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage build() {
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage buildPartial() {
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage result = new com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage(this);
        int from_bitField0_ = bitField0_;
        if (instructionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            instruction_ = java.util.Collections.unmodifiableList(instruction_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.instruction_ = instruction_;
        } else {
          result.instruction_ = instructionBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage) {
          return mergeFrom((com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage other) {
        if (other == com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage.getDefaultInstance()) return this;
        if (instructionBuilder_ == null) {
          if (!other.instruction_.isEmpty()) {
            if (instruction_.isEmpty()) {
              instruction_ = other.instruction_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInstructionIsMutable();
              instruction_.addAll(other.instruction_);
            }
            onChanged();
          }
        } else {
          if (!other.instruction_.isEmpty()) {
            if (instructionBuilder_.isEmpty()) {
              instructionBuilder_.dispose();
              instructionBuilder_ = null;
              instruction_ = other.instruction_;
              bitField0_ = (bitField0_ & ~0x00000001);
              instructionBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInstructionFieldBuilder() : null;
            } else {
              instructionBuilder_.addAllMessages(other.instruction_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getInstructionCount(); i++) {
          if (!getInstruction(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction> instruction_ =
        java.util.Collections.emptyList();
      private void ensureInstructionIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          instruction_ = new java.util.ArrayList<com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction>(instruction_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction, com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.Builder, com.toocol.ssh.core.mosh.core.proto.UserInputPB.InstructionOrBuilder> instructionBuilder_;

      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public java.util.List<com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction> getInstructionList() {
        if (instructionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(instruction_);
        } else {
          return instructionBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public int getInstructionCount() {
        if (instructionBuilder_ == null) {
          return instruction_.size();
        } else {
          return instructionBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction getInstruction(int index) {
        if (instructionBuilder_ == null) {
          return instruction_.get(index);
        } else {
          return instructionBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public Builder setInstruction(
          int index, com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction value) {
        if (instructionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstructionIsMutable();
          instruction_.set(index, value);
          onChanged();
        } else {
          instructionBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public Builder setInstruction(
          int index, com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.Builder builderForValue) {
        if (instructionBuilder_ == null) {
          ensureInstructionIsMutable();
          instruction_.set(index, builderForValue.build());
          onChanged();
        } else {
          instructionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public Builder addInstruction(com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction value) {
        if (instructionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstructionIsMutable();
          instruction_.add(value);
          onChanged();
        } else {
          instructionBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public Builder addInstruction(
          int index, com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction value) {
        if (instructionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstructionIsMutable();
          instruction_.add(index, value);
          onChanged();
        } else {
          instructionBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public Builder addInstruction(
          com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.Builder builderForValue) {
        if (instructionBuilder_ == null) {
          ensureInstructionIsMutable();
          instruction_.add(builderForValue.build());
          onChanged();
        } else {
          instructionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public Builder addInstruction(
          int index, com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.Builder builderForValue) {
        if (instructionBuilder_ == null) {
          ensureInstructionIsMutable();
          instruction_.add(index, builderForValue.build());
          onChanged();
        } else {
          instructionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public Builder addAllInstruction(
          java.lang.Iterable<? extends com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction> values) {
        if (instructionBuilder_ == null) {
          ensureInstructionIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, instruction_);
          onChanged();
        } else {
          instructionBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public Builder clearInstruction() {
        if (instructionBuilder_ == null) {
          instruction_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          instructionBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public Builder removeInstruction(int index) {
        if (instructionBuilder_ == null) {
          ensureInstructionIsMutable();
          instruction_.remove(index);
          onChanged();
        } else {
          instructionBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.Builder getInstructionBuilder(
          int index) {
        return getInstructionFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.InstructionOrBuilder getInstructionOrBuilder(
          int index) {
        if (instructionBuilder_ == null) {
          return instruction_.get(index);  } else {
          return instructionBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public java.util.List<? extends com.toocol.ssh.core.mosh.core.proto.UserInputPB.InstructionOrBuilder> 
           getInstructionOrBuilderList() {
        if (instructionBuilder_ != null) {
          return instructionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(instruction_);
        }
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.Builder addInstructionBuilder() {
        return getInstructionFieldBuilder().addBuilder(
            com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.getDefaultInstance());
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.Builder addInstructionBuilder(
          int index) {
        return getInstructionFieldBuilder().addBuilder(
            index, com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.getDefaultInstance());
      }
      /**
       * <code>repeated .ClientBuffers.Instruction instruction = 1;</code>
       */
      public java.util.List<com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.Builder> 
           getInstructionBuilderList() {
        return getInstructionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction, com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.Builder, com.toocol.ssh.core.mosh.core.proto.UserInputPB.InstructionOrBuilder> 
          getInstructionFieldBuilder() {
        if (instructionBuilder_ == null) {
          instructionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction, com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.Builder, com.toocol.ssh.core.mosh.core.proto.UserInputPB.InstructionOrBuilder>(
                  instruction_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          instruction_ = null;
        }
        return instructionBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ClientBuffers.UserMessage)
    }

    // @@protoc_insertion_point(class_scope:ClientBuffers.UserMessage)
    private static final com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage();
    }

    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<UserMessage>
        PARSER = new com.google.protobuf.AbstractParser<UserMessage>() {
      @java.lang.Override
      public UserMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.toocol.ssh.core.mosh.core.proto.UserInputPB.UserMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InstructionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientBuffers.Instruction)
      com.google.protobuf.GeneratedMessageV3.
          ExtendableMessageOrBuilder<Instruction> {
  }
  /**
   * Protobuf type {@code ClientBuffers.Instruction}
   */
  public static final class Instruction extends
      com.google.protobuf.GeneratedMessageV3.ExtendableMessage<
        Instruction> implements
      // @@protoc_insertion_point(message_implements:ClientBuffers.Instruction)
      InstructionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Instruction.newBuilder() to construct.
    private Instruction(com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction, ?> builder) {
      super(builder);
    }
    private Instruction() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Instruction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Instruction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_Instruction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_Instruction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.class, com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .ExtendableMessage<com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction>.ExtensionWriter
          extensionWriter = newExtensionWriter();
      extensionWriter.writeUntil(536870912, output);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += extensionsSerializedSize();
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction)) {
        return super.equals(obj);
      }
      com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction other = (com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      if (!getExtensionFields().equals(other.getExtensionFields()))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = hashFields(hash, getExtensionFields());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientBuffers.Instruction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.ExtendableBuilder<
          com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction, Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientBuffers.Instruction)
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.InstructionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_Instruction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_Instruction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.class, com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.Builder.class);
      }

      // Construct using com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_Instruction_descriptor;
      }

      @java.lang.Override
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction getDefaultInstanceForType() {
        return com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.getDefaultInstance();
      }

      @java.lang.Override
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction build() {
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction buildPartial() {
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction result = new com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction, Type> extension,
          Type value) {
        return super.setExtension(extension, value);
      }
      @java.lang.Override
      public <Type> Builder setExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction, java.util.List<Type>> extension,
          int index, Type value) {
        return super.setExtension(extension, index, value);
      }
      @java.lang.Override
      public <Type> Builder addExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction, java.util.List<Type>> extension,
          Type value) {
        return super.addExtension(extension, value);
      }
      @java.lang.Override
      public <Type> Builder clearExtension(
          com.google.protobuf.GeneratedMessage.GeneratedExtension<
              com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction, ?> extension) {
        return super.clearExtension(extension);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction) {
          return mergeFrom((com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction other) {
        if (other == com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction.getDefaultInstance()) return this;
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!extensionsAreInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ClientBuffers.Instruction)
    }

    // @@protoc_insertion_point(class_scope:ClientBuffers.Instruction)
    private static final com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction();
    }

    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Instruction>
        PARSER = new com.google.protobuf.AbstractParser<Instruction>() {
      @java.lang.Override
      public Instruction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Instruction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Instruction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Instruction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KeystrokeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientBuffers.Keystroke)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes keys = 4;</code>
     * @return Whether the keys field is set.
     */
    boolean hasKeys();
    /**
     * <code>optional bytes keys = 4;</code>
     * @return The keys.
     */
    com.google.protobuf.ByteString getKeys();
  }
  /**
   * Protobuf type {@code ClientBuffers.Keystroke}
   */
  public static final class Keystroke extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ClientBuffers.Keystroke)
      KeystrokeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Keystroke.newBuilder() to construct.
    private Keystroke(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Keystroke() {
      keys_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Keystroke();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Keystroke(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 34: {
              bitField0_ |= 0x00000001;
              keys_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_Keystroke_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_Keystroke_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke.class, com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke.Builder.class);
    }

    private int bitField0_;
    public static final int KEYS_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString keys_;
    /**
     * <code>optional bytes keys = 4;</code>
     * @return Whether the keys field is set.
     */
    @java.lang.Override
    public boolean hasKeys() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes keys = 4;</code>
     * @return The keys.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKeys() {
      return keys_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(4, keys_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, keys_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke)) {
        return super.equals(obj);
      }
      com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke other = (com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke) obj;

      if (hasKeys() != other.hasKeys()) return false;
      if (hasKeys()) {
        if (!getKeys()
            .equals(other.getKeys())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasKeys()) {
        hash = (37 * hash) + KEYS_FIELD_NUMBER;
        hash = (53 * hash) + getKeys().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientBuffers.Keystroke}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientBuffers.Keystroke)
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.KeystrokeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_Keystroke_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_Keystroke_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke.class, com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke.Builder.class);
      }

      // Construct using com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        keys_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_Keystroke_descriptor;
      }

      @java.lang.Override
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke getDefaultInstanceForType() {
        return com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke.getDefaultInstance();
      }

      @java.lang.Override
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke build() {
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke buildPartial() {
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke result = new com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.keys_ = keys_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke) {
          return mergeFrom((com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke other) {
        if (other == com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke.getDefaultInstance()) return this;
        if (other.hasKeys()) {
          setKeys(other.getKeys());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString keys_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes keys = 4;</code>
       * @return Whether the keys field is set.
       */
      @java.lang.Override
      public boolean hasKeys() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes keys = 4;</code>
       * @return The keys.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getKeys() {
        return keys_;
      }
      /**
       * <code>optional bytes keys = 4;</code>
       * @param value The keys to set.
       * @return This builder for chaining.
       */
      public Builder setKeys(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        keys_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes keys = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeys() {
        bitField0_ = (bitField0_ & ~0x00000001);
        keys_ = getDefaultInstance().getKeys();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ClientBuffers.Keystroke)
    }

    // @@protoc_insertion_point(class_scope:ClientBuffers.Keystroke)
    private static final com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke();
    }

    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Keystroke>
        PARSER = new com.google.protobuf.AbstractParser<Keystroke>() {
      @java.lang.Override
      public Keystroke parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Keystroke(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Keystroke> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Keystroke> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResizeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientBuffers.ResizeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 width = 5;</code>
     * @return Whether the width field is set.
     */
    boolean hasWidth();
    /**
     * <code>optional int32 width = 5;</code>
     * @return The width.
     */
    int getWidth();

    /**
     * <code>optional int32 height = 6;</code>
     * @return Whether the height field is set.
     */
    boolean hasHeight();
    /**
     * <code>optional int32 height = 6;</code>
     * @return The height.
     */
    int getHeight();
  }
  /**
   * Protobuf type {@code ClientBuffers.ResizeMessage}
   */
  public static final class ResizeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ClientBuffers.ResizeMessage)
      ResizeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResizeMessage.newBuilder() to construct.
    private ResizeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResizeMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResizeMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResizeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 40: {
              bitField0_ |= 0x00000001;
              width_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000002;
              height_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_ResizeMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_ResizeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage.class, com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage.Builder.class);
    }

    private int bitField0_;
    public static final int WIDTH_FIELD_NUMBER = 5;
    private int width_;
    /**
     * <code>optional int32 width = 5;</code>
     * @return Whether the width field is set.
     */
    @java.lang.Override
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 width = 5;</code>
     * @return The width.
     */
    @java.lang.Override
    public int getWidth() {
      return width_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 6;
    private int height_;
    /**
     * <code>optional int32 height = 6;</code>
     * @return Whether the height field is set.
     */
    @java.lang.Override
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 height = 6;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(5, width_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(6, height_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, width_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, height_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage)) {
        return super.equals(obj);
      }
      com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage other = (com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage) obj;

      if (hasWidth() != other.hasWidth()) return false;
      if (hasWidth()) {
        if (getWidth()
            != other.getWidth()) return false;
      }
      if (hasHeight() != other.hasHeight()) return false;
      if (hasHeight()) {
        if (getHeight()
            != other.getHeight()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasWidth()) {
        hash = (37 * hash) + WIDTH_FIELD_NUMBER;
        hash = (53 * hash) + getWidth();
      }
      if (hasHeight()) {
        hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getHeight();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientBuffers.ResizeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientBuffers.ResizeMessage)
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_ResizeMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_ResizeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage.class, com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage.Builder.class);
      }

      // Construct using com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        width_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.toocol.ssh.core.mosh.core.proto.UserInputPB.internal_static_ClientBuffers_ResizeMessage_descriptor;
      }

      @java.lang.Override
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage getDefaultInstanceForType() {
        return com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage build() {
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage buildPartial() {
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage result = new com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.width_ = width_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.height_ = height_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage) {
          return mergeFrom((com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage other) {
        if (other == com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage.getDefaultInstance()) return this;
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int width_ ;
      /**
       * <code>optional int32 width = 5;</code>
       * @return Whether the width field is set.
       */
      @java.lang.Override
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 width = 5;</code>
       * @return The width.
       */
      @java.lang.Override
      public int getWidth() {
        return width_;
      }
      /**
       * <code>optional int32 width = 5;</code>
       * @param value The width to set.
       * @return This builder for chaining.
       */
      public Builder setWidth(int value) {
        bitField0_ |= 0x00000001;
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 width = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000001);
        width_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>optional int32 height = 6;</code>
       * @return Whether the height field is set.
       */
      @java.lang.Override
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 height = 6;</code>
       * @return The height.
       */
      @java.lang.Override
      public int getHeight() {
        return height_;
      }
      /**
       * <code>optional int32 height = 6;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000002;
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 height = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000002);
        height_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ClientBuffers.ResizeMessage)
    }

    // @@protoc_insertion_point(class_scope:ClientBuffers.ResizeMessage)
    private static final com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage();
    }

    public static com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ResizeMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResizeMessage>() {
      @java.lang.Override
      public ResizeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResizeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResizeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResizeMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int KEYSTROKE_FIELD_NUMBER = 2;
  /**
   * <code>extend .ClientBuffers.Instruction { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction,
      com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke> keystroke = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke.class,
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.Keystroke.getDefaultInstance());
  public static final int RESIZE_FIELD_NUMBER = 3;
  /**
   * <code>extend .ClientBuffers.Instruction { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.toocol.ssh.core.mosh.core.proto.UserInputPB.Instruction,
      com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage> resize = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage.class,
        com.toocol.ssh.core.mosh.core.proto.UserInputPB.ResizeMessage.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientBuffers_UserMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientBuffers_UserMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientBuffers_Instruction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientBuffers_Instruction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientBuffers_Keystroke_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientBuffers_Keystroke_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientBuffers_ResizeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientBuffers_ResizeMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017userinput.proto\022\rClientBuffers\">\n\013User" +
      "Message\022/\n\013instruction\030\001 \003(\0132\032.ClientBuf" +
      "fers.Instruction\"\027\n\013Instruction*\010\010\002\020\200\200\200\200" +
      "\002\"\031\n\tKeystroke\022\014\n\004keys\030\004 \001(\014\".\n\rResizeMe" +
      "ssage\022\r\n\005width\030\005 \001(\005\022\016\n\006height\030\006 \001(\005:G\n\t" +
      "keystroke\022\032.ClientBuffers.Instruction\030\002 " +
      "\001(\0132\030.ClientBuffers.Keystroke:H\n\006resize\022" +
      "\032.ClientBuffers.Instruction\030\003 \001(\0132\034.Clie" +
      "ntBuffers.ResizeMessageB4\n#com.toocol.ss" +
      "h.core.mosh.core.protoB\013UserInputPBH\003"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ClientBuffers_UserMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientBuffers_UserMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientBuffers_UserMessage_descriptor,
        new java.lang.String[] { "Instruction", });
    internal_static_ClientBuffers_Instruction_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ClientBuffers_Instruction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientBuffers_Instruction_descriptor,
        new java.lang.String[] { });
    internal_static_ClientBuffers_Keystroke_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ClientBuffers_Keystroke_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientBuffers_Keystroke_descriptor,
        new java.lang.String[] { "Keys", });
    internal_static_ClientBuffers_ResizeMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ClientBuffers_ResizeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientBuffers_ResizeMessage_descriptor,
        new java.lang.String[] { "Width", "Height", });
    keystroke.internalInit(descriptor.getExtensions().get(0));
    resize.internalInit(descriptor.getExtensions().get(1));
  }

  // @@protoc_insertion_point(outer_class_scope)
}
