/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_toocol_ssh_common_jni_TermioJNI */

#ifndef _Included_com_toocol_ssh_common_jni_TermioJNI
#define _Included_com_toocol_ssh_common_jni_TermioJNI
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_toocol_ssh_common_jni_TermioJNI
 * Method:    chooseFiles
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_toocol_ssh_common_jni_TermioJNI_chooseFiles
  (JNIEnv *, jobject);

/*
 * Class:     com_toocol_ssh_common_jni_TermioJNI
 * Method:    chooseDirectory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_toocol_ssh_common_jni_TermioJNI_chooseDirectory
  (JNIEnv *, jobject);

/*
 * Class:     com_toocol_ssh_common_jni_TerminatioJNI
 * Method:    getWindowWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_toocol_ssh_common_jni_TermioJNI_getWindowWidth
        (JNIEnv *, jobject);

/*
 * Class:     com_toocol_ssh_common_jni_TerminatioJNI
 * Method:    getWindowHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_toocol_ssh_common_jni_TermioJNI_getWindowHeight
        (JNIEnv *, jobject);

/*
 * Class:     com_toocol_ssh_common_jni_TermioJNI
 * Method:    getCursorPosition
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_toocol_ssh_common_jni_TermioJNI_getCursorPosition
  (JNIEnv *, jobject);

/*
 * Class:     com_toocol_ssh_common_jni_TermioJNI
 * Method:    setCursorPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_toocol_ssh_common_jni_TermioJNI_setCursorPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_toocol_ssh_common_jni_TermioJNI
 * Method:    cursorBackLine
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_toocol_ssh_common_jni_TermioJNI_cursorBackLine
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_toocol_ssh_common_jni_TermioJNI
 * Method:    showCursor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_toocol_ssh_common_jni_TermioJNI_showCursor
  (JNIEnv *, jobject);

/*
 * Class:     com_toocol_ssh_common_jni_TermioJNI
 * Method:    hideCursor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_toocol_ssh_common_jni_TermioJNI_hideCursor
  (JNIEnv *, jobject);

/*
 * Class:     com_toocol_ssh_common_jni_TermioJNI
 * Method:    cursorLeft
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_toocol_ssh_common_jni_TermioJNI_cursorLeft
  (JNIEnv *, jobject);

/*
 * Class:     com_toocol_ssh_common_jni_TermioJNI
 * Method:    cursorRight
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_toocol_ssh_common_jni_TermioJNI_cursorRight
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
