// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc 3.19.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `transportinstruction.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:TransportBuffers.Instruction)
pub struct Instruction {
    // message fields
    // @@protoc_insertion_point(field:TransportBuffers.Instruction.protocol_version)
    pub protocol_version: ::std::option::Option<u32>,
    // @@protoc_insertion_point(field:TransportBuffers.Instruction.old_num)
    pub old_num: ::std::option::Option<u64>,
    // @@protoc_insertion_point(field:TransportBuffers.Instruction.new_num)
    pub new_num: ::std::option::Option<u64>,
    // @@protoc_insertion_point(field:TransportBuffers.Instruction.ack_num)
    pub ack_num: ::std::option::Option<u64>,
    // @@protoc_insertion_point(field:TransportBuffers.Instruction.throwaway_num)
    pub throwaway_num: ::std::option::Option<u64>,
    // @@protoc_insertion_point(field:TransportBuffers.Instruction.diff)
    pub diff: ::std::option::Option<::std::vec::Vec<u8>>,
    // @@protoc_insertion_point(field:TransportBuffers.Instruction.chaff)
    pub chaff: ::std::option::Option<::std::vec::Vec<u8>>,
    // special fields
    // @@protoc_insertion_point(special_field:TransportBuffers.Instruction.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Instruction {
    fn default() -> &'a Instruction {
        <Instruction as ::protobuf::Message>::default_instance()
    }
}

impl Instruction {
    pub fn new() -> Instruction {
        ::std::default::Default::default()
    }

    // optional uint32 protocol_version = 1;

    pub fn protocol_version(&self) -> u32 {
        self.protocol_version.unwrap_or(0)
    }

    pub fn clear_protocol_version(&mut self) {
        self.protocol_version = ::std::option::Option::None;
    }

    pub fn has_protocol_version(&self) -> bool {
        self.protocol_version.is_some()
    }

    // Param is passed by value, moved
    pub fn set_protocol_version(&mut self, v: u32) {
        self.protocol_version = ::std::option::Option::Some(v);
    }

    // optional uint64 old_num = 2;

    pub fn old_num(&self) -> u64 {
        self.old_num.unwrap_or(0)
    }

    pub fn clear_old_num(&mut self) {
        self.old_num = ::std::option::Option::None;
    }

    pub fn has_old_num(&self) -> bool {
        self.old_num.is_some()
    }

    // Param is passed by value, moved
    pub fn set_old_num(&mut self, v: u64) {
        self.old_num = ::std::option::Option::Some(v);
    }

    // optional uint64 new_num = 3;

    pub fn new_num(&self) -> u64 {
        self.new_num.unwrap_or(0)
    }

    pub fn clear_new_num(&mut self) {
        self.new_num = ::std::option::Option::None;
    }

    pub fn has_new_num(&self) -> bool {
        self.new_num.is_some()
    }

    // Param is passed by value, moved
    pub fn set_new_num(&mut self, v: u64) {
        self.new_num = ::std::option::Option::Some(v);
    }

    // optional uint64 ack_num = 4;

    pub fn ack_num(&self) -> u64 {
        self.ack_num.unwrap_or(0)
    }

    pub fn clear_ack_num(&mut self) {
        self.ack_num = ::std::option::Option::None;
    }

    pub fn has_ack_num(&self) -> bool {
        self.ack_num.is_some()
    }

    // Param is passed by value, moved
    pub fn set_ack_num(&mut self, v: u64) {
        self.ack_num = ::std::option::Option::Some(v);
    }

    // optional uint64 throwaway_num = 5;

    pub fn throwaway_num(&self) -> u64 {
        self.throwaway_num.unwrap_or(0)
    }

    pub fn clear_throwaway_num(&mut self) {
        self.throwaway_num = ::std::option::Option::None;
    }

    pub fn has_throwaway_num(&self) -> bool {
        self.throwaway_num.is_some()
    }

    // Param is passed by value, moved
    pub fn set_throwaway_num(&mut self, v: u64) {
        self.throwaway_num = ::std::option::Option::Some(v);
    }

    // optional bytes diff = 6;

    pub fn diff(&self) -> &[u8] {
        match self.diff.as_ref() {
            Some(v) => v,
            None => &[],
        }
    }

    pub fn clear_diff(&mut self) {
        self.diff = ::std::option::Option::None;
    }

    pub fn has_diff(&self) -> bool {
        self.diff.is_some()
    }

    // Param is passed by value, moved
    pub fn set_diff(&mut self, v: ::std::vec::Vec<u8>) {
        self.diff = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_diff(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.diff.is_none() {
            self.diff = ::std::option::Option::Some(::std::vec::Vec::new());
        }
        self.diff.as_mut().unwrap()
    }

    // Take field
    pub fn take_diff(&mut self) -> ::std::vec::Vec<u8> {
        self.diff.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    // optional bytes chaff = 7;

    pub fn chaff(&self) -> &[u8] {
        match self.chaff.as_ref() {
            Some(v) => v,
            None => &[],
        }
    }

    pub fn clear_chaff(&mut self) {
        self.chaff = ::std::option::Option::None;
    }

    pub fn has_chaff(&self) -> bool {
        self.chaff.is_some()
    }

    // Param is passed by value, moved
    pub fn set_chaff(&mut self, v: ::std::vec::Vec<u8>) {
        self.chaff = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_chaff(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.chaff.is_none() {
            self.chaff = ::std::option::Option::Some(::std::vec::Vec::new());
        }
        self.chaff.as_mut().unwrap()
    }

    // Take field
    pub fn take_chaff(&mut self) -> ::std::vec::Vec<u8> {
        self.chaff.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(7);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "protocol_version",
            |m: &Instruction| { &m.protocol_version },
            |m: &mut Instruction| { &mut m.protocol_version },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "old_num",
            |m: &Instruction| { &m.old_num },
            |m: &mut Instruction| { &mut m.old_num },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "new_num",
            |m: &Instruction| { &m.new_num },
            |m: &mut Instruction| { &mut m.new_num },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "ack_num",
            |m: &Instruction| { &m.ack_num },
            |m: &mut Instruction| { &mut m.ack_num },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "throwaway_num",
            |m: &Instruction| { &m.throwaway_num },
            |m: &mut Instruction| { &mut m.throwaway_num },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "diff",
            |m: &Instruction| { &m.diff },
            |m: &mut Instruction| { &mut m.diff },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "chaff",
            |m: &Instruction| { &m.chaff },
            |m: &mut Instruction| { &mut m.chaff },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Instruction>(
            "Instruction",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Instruction {
    const NAME: &'static str = "Instruction";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.protocol_version = ::std::option::Option::Some(is.read_uint32()?);
                },
                16 => {
                    self.old_num = ::std::option::Option::Some(is.read_uint64()?);
                },
                24 => {
                    self.new_num = ::std::option::Option::Some(is.read_uint64()?);
                },
                32 => {
                    self.ack_num = ::std::option::Option::Some(is.read_uint64()?);
                },
                40 => {
                    self.throwaway_num = ::std::option::Option::Some(is.read_uint64()?);
                },
                50 => {
                    self.diff = ::std::option::Option::Some(is.read_bytes()?);
                },
                58 => {
                    self.chaff = ::std::option::Option::Some(is.read_bytes()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.protocol_version {
            my_size += ::protobuf::rt::uint32_size(1, v);
        }
        if let Some(v) = self.old_num {
            my_size += ::protobuf::rt::uint64_size(2, v);
        }
        if let Some(v) = self.new_num {
            my_size += ::protobuf::rt::uint64_size(3, v);
        }
        if let Some(v) = self.ack_num {
            my_size += ::protobuf::rt::uint64_size(4, v);
        }
        if let Some(v) = self.throwaway_num {
            my_size += ::protobuf::rt::uint64_size(5, v);
        }
        if let Some(v) = self.diff.as_ref() {
            my_size += ::protobuf::rt::bytes_size(6, &v);
        }
        if let Some(v) = self.chaff.as_ref() {
            my_size += ::protobuf::rt::bytes_size(7, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.protocol_version {
            os.write_uint32(1, v)?;
        }
        if let Some(v) = self.old_num {
            os.write_uint64(2, v)?;
        }
        if let Some(v) = self.new_num {
            os.write_uint64(3, v)?;
        }
        if let Some(v) = self.ack_num {
            os.write_uint64(4, v)?;
        }
        if let Some(v) = self.throwaway_num {
            os.write_uint64(5, v)?;
        }
        if let Some(v) = self.diff.as_ref() {
            os.write_bytes(6, v)?;
        }
        if let Some(v) = self.chaff.as_ref() {
            os.write_bytes(7, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Instruction {
        Instruction::new()
    }

    fn clear(&mut self) {
        self.protocol_version = ::std::option::Option::None;
        self.old_num = ::std::option::Option::None;
        self.new_num = ::std::option::Option::None;
        self.ack_num = ::std::option::Option::None;
        self.throwaway_num = ::std::option::Option::None;
        self.diff = ::std::option::Option::None;
        self.chaff = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Instruction {
        static instance: Instruction = Instruction {
            protocol_version: ::std::option::Option::None,
            old_num: ::std::option::Option::None,
            new_num: ::std::option::Option::None,
            ack_num: ::std::option::Option::None,
            throwaway_num: ::std::option::Option::None,
            diff: ::std::option::Option::None,
            chaff: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Instruction {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Instruction").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Instruction {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Instruction {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1atransportinstruction.proto\x12\x10TransportBuffers\"\xd2\x01\n\x0b\
    Instruction\x12)\n\x10protocol_version\x18\x01\x20\x01(\rR\x0fprotocolVe\
    rsion\x12\x17\n\x07old_num\x18\x02\x20\x01(\x04R\x06oldNum\x12\x17\n\x07\
    new_num\x18\x03\x20\x01(\x04R\x06newNum\x12\x17\n\x07ack_num\x18\x04\x20\
    \x01(\x04R\x06ackNum\x12#\n\rthrowaway_num\x18\x05\x20\x01(\x04R\x0cthro\
    wawayNum\x12\x12\n\x04diff\x18\x06\x20\x01(\x0cR\x04diff\x12\x14\n\x05ch\
    aff\x18\x07\x20\x01(\x0cR\x05chaffB\x02H\x03\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(Instruction::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
